DEFAULT alpine
PROMPT 1
TIMEOUT 20

LABEL alpine
    MENU LABEL AIDOS Alpine
    LINUX /boot/vmlinuz-virt
    INITRD /boot/initramfs-virt
    APPEND root=/dev/sda1 modules=sd-mod,usb-storage,ext4 quiet cpufreq.default_governor=performance nohz_full=1-3
